name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install API dependencies
        working-directory: api
        run: npm install

      - name: Run backend tests
        working-directory: api
        run: npm test

      - name: Install web-portal dependencies
        working-directory: web-portal
        run: npm install

      - name: Lint web-portal
        working-directory: web-portal
        run: npm run lint || echo "Lint skipped"

      - name: Build web-portal
        working-directory: web-portal
        run: npm run build

      - name: Deploy to Vercel
        run: npx vercel --prod --yes
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - name: Install mobile-app dependencies
        working-directory: mobile-app
        run: npm install

      - name: Publish to Expo
        working-directory: mobile-app
        run: npx expo publish
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Echo deployment success
        run: |
          echo "✅ CI/CD Pipeline completed successfully!"
          echo "🔗 Web App Preview (Vercel): https://<your-vercel-project>.vercel.app"
          echo "📱 Mobile App Preview (Expo): https://expo.dev/@<your-expo-username>/ghana-road-toll"