name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install --workspaces

      - name: Lint
        run: npm run lint --workspaces

      - name: Run tests with coverage
        run: npm test --workspaces -- --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build web-portal
        run: npm run build --workspace=web-portal

      - name: Deploy to Vercel
        run: npx vercel --prod --confirm
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - name: Publish to Expo
        run: npx expo publish
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Echo deployment success
        run: |
          echo "✅ CI/CD Pipeline completed successfully!"
          echo "🔗 Web App Preview (Vercel): https://<your-vercel-project>.vercel.app"
          echo "📱 Mobile App Preview (Expo): https://expo.dev/@<your-expo-username>/ghana-road-toll"